package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"time"

	"github.com/enuesaa/walkin/pkg/graph/model"
	"github.com/enuesaa/walkin/pkg/invoke"
	"github.com/enuesaa/walkin/pkg/repository"
	"github.com/google/uuid"
)

// Invocations is the resolver for the invocations field.
func (r *queryResolver) Invocations(ctx context.Context, status int) ([]*model.Invocation, error) {
	list := make([]*model.Invocation, 0)

	repos := repository.NewRepos()
	invocations, err := invoke.ListLogs(repos)
	if err != nil {
		return make([]*model.Invocation, 0), err
	}
	list = make([]*model.Invocation, 0)
	for i, invocation := range invocations {
		list = append(list, &model.Invocation{
			ID: fmt.Sprintf("%d", i),
			Status: invocation.Status,
			Method: invocation.Method,
			URL: invocation.Url,
			RequestHeaders: make([]*model.Header, 0),
			ResponseHeaders: make([]*model.Header, 0),
			RequestBody: &invocation.RequestBody,
			ResponseBody: &invocation.ResponseBody,
		})
	}

	return list, nil
}

// Name is the resolver for the name field.
func (r *subscriptionResolver) Name(ctx context.Context) (<-chan string, error) {
	ch := make(chan string)

	go func() {
		defer close(ch)
		for {
			time.Sleep(1 * time.Second)
			t := uuid.New().String()
			select {
			case <-ctx.Done():
				fmt.Println("Subscription Closed")
				return
			case ch <- t: // This is the actual send.
			}
		}
	}()

	return ch, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
