package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"time"

	"github.com/enuesaa/walkin/pkg/invoke"
	"github.com/enuesaa/walkin/pkg/repository"
)

// Invocations is the resolver for the invocations field.
func (r *queryResolver) Invocations(ctx context.Context) ([]*Invocation, error) {
	list := make([]*Invocation, 0)

	repos := repository.NewRepos()
	invocations, err := invoke.ListLogs(repos)
	if err != nil {
		return make([]*Invocation, 0), err
	}
	list = make([]*Invocation, 0)
	for _, invocation := range invocations {
		list = append(list, &Invocation{
			ID:              invocation.Id,
			Status:          invocation.Status,
			Method:          invocation.Method,
			URL:             invocation.Url,
			RequestHeaders:  make([]*Header, 0),
			ResponseHeaders: make([]*Header, 0),
			RequestBody:     &invocation.RequestBody,
			ResponseBody:    &invocation.ResponseBody,
		})
	}

	return list, nil
}

// Invocation is the resolver for the invocation field.
func (r *queryResolver) Invocation(ctx context.Context, id string) (*Invocation, error) {
	repos := repository.NewRepos()
	invocations, err := invoke.ListLogs(repos)
	if err != nil {
		return nil, err
	}
	// todo: refator
	for _, invocation := range invocations {
		if invocation.Id == id {
			return &Invocation{
				ID:              invocation.Id,
				Status:          invocation.Status,
				Method:          invocation.Method,
				URL:             invocation.Url,
				RequestHeaders:  make([]*Header, 0),
				ResponseHeaders: make([]*Header, 0),
				RequestBody:     &invocation.RequestBody,
				ResponseBody:    &invocation.ResponseBody,
			}, nil
		}
	}

	return nil, fmt.Errorf("not found")
}

// Invocations is the resolver for the invocations field.
func (r *subscriptionResolver) Invocations(ctx context.Context) (<-chan []*Invocation, error) {
	ch := make(chan []*Invocation)
	repos := repository.NewRepos()

	go func() {
		defer close(ch)
		for {
			time.Sleep(1 * time.Second)
			invocations, err := invoke.ListLogs(repos)
			if err != nil {
				continue
			}
			list := make([]*Invocation, 0)
			for _, invocation := range invocations {
				list = append(list, &Invocation{
					ID:              invocation.Id,
					Status:          invocation.Status,
					Method:          invocation.Method,
					URL:             invocation.Url,
					RequestHeaders:  make([]*Header, 0),
					ResponseHeaders: make([]*Header, 0),
					RequestBody:     &invocation.RequestBody,
					ResponseBody:    &invocation.ResponseBody,
				})
			}
			select {
			case <-ctx.Done():
				fmt.Println("Subscription Closed")
				return
			case ch <- list:
			}
		}
	}()

	return ch, nil
}

type Resolver struct{}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
