// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Header struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type Invocation struct {
	ID              string    `json:"id"`
	Status          int       `json:"status"`
	Method          string    `json:"method"`
	URL             string    `json:"url"`
	RequestHeaders  []*Header `json:"requestHeaders,omitempty"`
	ResponseHeaders []*Header `json:"responseHeaders,omitempty"`
	RequestBody     *string   `json:"requestBody,omitempty"`
	ResponseBody    *string   `json:"responseBody,omitempty"`
}

type Query struct {
}
