package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/enuesaa/walkin/graph/model"
)

// Invocatoins is the resolver for the invocatoins field.
func (r *queryResolver) Invocatoins(ctx context.Context) ([]*model.Invocation, error) {
	panic(fmt.Errorf("not implemented: Invocatoins - invocatoins"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
