// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package invoke

type BrowserInvocationInput struct {
	Status          int            `json:"status"`
	Method          string         `json:"method"`
	URL             string         `json:"url"`
	RequestHeaders  []*HeaderInput `json:"requestHeaders,omitempty"`
	ResponseHeaders []*HeaderInput `json:"responseHeaders,omitempty"`
	RequestBody     string         `json:"requestBody"`
	ResponseBody    string         `json:"responseBody"`
}

type Header struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type HeaderInput struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type Invocation struct {
	ID              string    `json:"id"`
	Status          int       `json:"status"`
	Method          string    `json:"method"`
	URL             string    `json:"url"`
	RequestHeaders  []*Header `json:"requestHeaders,omitempty"`
	ResponseHeaders []*Header `json:"responseHeaders,omitempty"`
	RequestBody     string    `json:"requestBody"`
	ResponseBody    string    `json:"responseBody"`
}

type Mutation struct {
}

type Query struct {
}

type ServerInvocationInput struct {
	Method         string         `json:"method"`
	URL            string         `json:"url"`
	RequestHeaders []*HeaderInput `json:"requestHeaders,omitempty"`
	RequestBody    string         `json:"requestBody"`
}

type Subscription struct {
}
