package invoke

// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"time"
)

func (r *queryResolver) Invocations(ctx context.Context) ([]*Invocation, error) {
	return ListLogs(r.repos)
}

func (r *queryResolver) Invocation(ctx context.Context, id string) (*Invocation, error) {
	return GetLog(r.repos, id)
}

func (r *subscriptionResolver) Invocations(ctx context.Context) (<-chan []*Invocation, error) {
	ch := make(chan []*Invocation)

	go func() {
		defer close(ch)
		for {
			time.Sleep(1 * time.Second)
			invocations, err := ListLogs(r.repos)
			if err != nil {
				continue
			}
			select {
			case <-ctx.Done():
				return
			case ch <- invocations:
			}
		}
	}()

	return ch, nil
}

func (r *Resolver) Query() QueryResolver {
	return &queryResolver{r}
}

func (r *Resolver) Subscription() SubscriptionResolver {
	return &subscriptionResolver{r}
}
